blank_issues_enabled: false
contact_links:
  - name: Support Request
    url: https://motivecreate.wixsite.com/home
    about: Please ask support questions on our official webpage instead of opening an issue.
